language: c
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
  # Install nim
  - git clone -b devel git://github.com/nim-lang/Nim.git --depth 1
  - cd Nim
  - git clone --depth 1 git://github.com/nim-lang/csources
  - cd csources && sh build.sh
  - cd ..
  - bin/nim c koch
  # -d:nimEmulateOverflowChecks is workaround for "undefined reference to __builtin_saddll_overflow",
  # see: Nim 1.2.0 release notes
  - ./koch boot -d:release -d:nimEmulateOverflowChecks
  - export PATH=$PWD/bin:$PATH
  - ./koch nimble -d:nimEmulateOverflowChecks
  - cd ..
  - nimble install -y
script:
  - nimble test

